name: AWS CDK Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
            npm install -g aws-cdk
            pip install -r requirements.txt

      - name: Boostrap CDK
        run: cdk bootstrap
        env: 
          APP_NAME: ${{ secrets.APP_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID }}

      - name: Deploy to AWS
        run: cdk deploy --all --require-approval never
        env: 
          APP_NAME: ${{ secrets.APP_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID }}